---
- name: Simulate basic server setup
  hosts: localhost
  gather_facts: false

  vars:
    common_packages:
      - curl
      - vim
      - git
      - htop
    upgrade_mode: dist

  tasks:
    - name: Upgrade_packages
      ansible.builtin.debug:
        msg: |
          TASK [Ensure latest updates are installed]
          ok: [{{ inventory_hostname }}] => {
              "upgrade_mode": "{{ upgrade_mode }}",
              "msg": "System packages are already up to date"
          }

    - name: Install_packages
      ansible.builtin.debug:
        msg: |
          TASK [Install common packages]
          changed: [{{ inventory_hostname }}] => {
              "packages_installed": {{ common_packages | to_nice_json }},
              "msg": "Installed successfully"
          }
