---
- name: Database configuration
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Configure_database
      ansible.builtin.debug:
        msg: |
          TASK [Configure database]
          changed: [{{ inventory_hostname }}] => {
              "db_name": "{{ db_name }}",
              "user": "{{ db_user }}",
          }
