---
- name: Simulate Flask app deployment
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Cloning_repo
      ansible.builtin.debug:
        msg: |
          TASK [Clone app repository]
          changed: [{{ inventory_hostname }}] => {
              "repo": "{{ repo_url }}",
              "version": "{{ app_version }}"
          }

    - name: Environment_setup
      ansible.builtin.debug:
        msg: |
          TASK [Set environment]
          ok: [{{ inventory_hostname }}] => {
              "environment": "{{ env }}",
              "app_name": "{{ app_name }}"
          }
