---
- name: Simulate user setup with prompts
  hosts: localhost
  gather_facts: false

  vars_prompt:
    - name: "username"
      prompt: "Enter the username to create"
      private: false
    - name: "user_group"
      prompt: "Enter the primary group"
      default: "sudo"
    - name: "ssh_key_path"
      prompt: "Enter path to public key file"
      private: false

  tasks:
    - name: Create_user
      ansible.builtin.debug:
        msg: |
          TASK [Ensure user exists]
          changed: [{{ inventory_hostname }}] => {
              "user": "{{ username }}",
              "group": "{{ user_group }}"
          }

    - name: Add_ssh_key
      ansible.builtin.debug:
        msg: |
          TASK [Add SSH key]
          ok: [{{ inventory_hostname }}] => {
              "user": "{{ username }}",
              "key_source": "{{ ssh_key_path }}"
          }
