---
- name: Simulate user setup with prompts
  hosts: all
  gather_facts: false

  vars_prompt:
    - name: "username"
      prompt: "Enter the username to create"
      private: no
    - name: "user_group"
      prompt: "Enter the primary group"
      default: "sudo"
    - name: "ssh_key_path"
      prompt: "Enter path to public key file"
      private: no

  tasks:
    - name: Log_create_user
      debug:
        msg: |
          TASK [Ensure user exists]
          changed: [{{ inventory_hostname }}] => {
              "user": "{{ username }}",
              "group": "{{ user_group }}"
          }

    - name: Log_add_ssh_key
      debug:
        msg: |
          TASK [Add SSH key]
          ok: [{{ inventory_hostname }}] => {
              "user": "{{ username }}",
              "key_source": "{{ ssh_key_path }}"
          }